### ISSUE TITLE
GL Error at startup: wirecage.frag shader compilation fails

### ISSUE THREAD

**Issue by murraycu** [danielkitta/somato#2]
There seems to be a problem with the wirecage.frag syntax. I don't know shader syntax at all.

At startup, I see:
** (somato:20660): CRITICAL **: unhandled exception in signal handler: GL error: Compiling /opt/gnome/share/somato/shaders/wirecage.frag failed

**Comment by danielkitta** [comment]
Hm. textlabel.frag is affected as well. Disabling both shaders makes the rest work. I'll try to find out what's going on.

**Comment by danielkitta** [comment]
Apparently it didn't like my use of component swizzles on scalars anymore. Fixed now.
